### ISSUE TITLE
NPE in SplitFactoryBuilder

### ISSUE THREAD

**Issue by tasegula** [splitio/android-client#108]
I was using a Charles proxy when running the app and it crashed due to a NPE in `SplitFactoryBuilder`, probably because it couldn't connect to the server / ERR_CONNECTION_REFUSED. 
This should be avoidable by returning empty lists instead of nulls.

The call:

```
// Build SDK configuration by default
val config: SplitClientConfig = SplitClientConfig.builder().build()

// Create a new user key to be evaluated
val key = Key(lastId, null)

// Create factory
val splitFactory: SplitFactory = SplitFactoryBuilder.build(SPLIT_API_KEY, key, config, context)
```

Stacktrace:
```
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List io.split.android.client.impressions.StoredImpressions.impressions()' on a null object reference
        at io.split.android.client.impressions.ImpressionsFileStorage.read(ImpressionsFileStorage.java:75)
        at io.split.android.client.impressions.ImpressionsStorageManager.loadEventsFilesByLine(ImpressionsStorageManager.java:187)
        at io.split.android.client.impressions.ImpressionsStorageManager.loadImpressionsFromDisk(ImpressionsStorageManager.java:182)
2019-10-14 11:26:51.938 6534-6640/dk.coop.coopplus.demo E/AndroidRuntime:     at io.split.android.client.impressions.ImpressionsStorageManager.<init>(ImpressionsStorageManager.java:63)
        at io.split.android.client.impressions.ImpressionsStorageManager.<init>(ImpressionsStorageManager.java:55)
        at io.split.android.client.SplitFactoryImpl.<init>(SplitFactoryImpl.java:151)
        at io.split.android.client.SplitFactoryBuilder.build(SplitFactoryBuilder.java:67)
```

**Comment by mredolatti** [comment]
Hi @tasegula !

Thank you very much for reaching out, we're sorry to hear that you're having issues with our SDK. Can you provide us with the Split SDK version you're using? A fix was released for a similar issue in version 2.4.4.

Thanks again.

**Comment by tasegula** [comment]
We're using `2.4.3`. I'll update and let you know if it's fixed with `2.4.4`. Thanks!

**Comment by mredolatti** [comment]
@tasegula Please update directly to 2.4.5 which fixes another small bug regarding a race condition. Thanks!

**Comment by tasegula** [comment]
Seems fixed now. I'll close. Thanks!
