### ISSUE TITLE
IllegalStateException: Problem fetching splitChanges: HttpException: Something happened while retrieving data: Chain validation failed

### ISSUE THREAD

**Issue by bogdanzurac** [splitio/android-client#135]
When setting the device date 2+ days in the future, the Split SDK HTTP calls fail with the below exception:

```
E/SplitSDK: RefreshableSplitFetcher failed: Problem fetching splitChanges: HttpException: Something happened while retrieving data: Chain validation failed
    java.lang.IllegalStateException: Problem fetching splitChanges: HttpException: Something happened while retrieving data: Chain validation failed
        at io.split.android.client.HttpSplitChangeFetcher.fetch(HttpSplitChangeFetcher.java:86)
        at io.split.android.client.HttpSplitChangeFetcher.fetch(HttpSplitChangeFetcher.java:52)
        at io.split.android.engine.experiments.RefreshableSplitFetcher.runWithoutExceptionHandling(RefreshableSplitFetcher.java:140)
        at io.split.android.engine.experiments.RefreshableSplitFetcher.run(RefreshableSplitFetcher.java:117)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:307)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:302)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: io.split.android.client.network.HttpException: HttpException: Something happened while retrieving data: Chain validation failed
        at io.split.android.client.network.HttpRequestImpl.getRequest(HttpRequestImpl.java:64)
        at io.split.android.client.network.HttpRequestImpl.execute(HttpRequestImpl.java:35)
        at io.split.android.client.HttpSplitChangeFetcher.fetch(HttpSplitChangeFetcher.java:72)
        at io.split.android.client.HttpSplitChangeFetcher.fetch(HttpSplitChangeFetcher.java:52) 
        at io.split.android.engine.experiments.RefreshableSplitFetcher.runWithoutExceptionHandling(RefreshableSplitFetcher.java:140) 
        at io.split.android.engine.experiments.RefreshableSplitFetcher.run(RefreshableSplitFetcher.java:117) 
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462) 
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:307) 
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:302) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919) 
```

**Comment by chillaq** [comment]
Thanks Bogdan for the info, I will repro and get Engineering involved.

Thanks
Bilal

**Comment by javrudsky** [comment]
A fix was issued for this ticket. Closing it because it has been inactive for mor than one year.
