### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException SqLitePersistentMySegmentsStorage

### ISSUE THREAD

**Issue by huhx0015** [splitio/android-client#218]
We've been seeing intermittent null pointer exception reports (via Crashlytics) originating from `SqLitePersistentMySegmentsStorage` from some of our users. This seems to have started ever since we upgraded the Split SDK dependency version to `2.6.6`. Is this a known issue?

```
Fatal Exception: java.lang.NullPointerException
       at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:890)
       at io.split.android.client.storage.mysegments.SqLitePersistentMySegmentsStorage.<init>(SqLitePersistentMySegmentsStorage.java:36)
       at io.split.android.client.storage.db.StorageFactory.getMySegmentsStorage(StorageFactory.java:31)
       at io.split.android.client.SplitFactoryHelper.buildStorageContainer(SplitFactoryHelper.java:68)
       at io.split.android.client.SplitFactoryImpl.<init>(SplitFactoryImpl.java:129)
       at io.split.android.client.SplitFactoryImpl.<init>(SplitFactoryImpl.java:80)
       at com.envoy.app.utils.SplitProvider.init(SplitProvider.java:67)
       at io.split.android.client.SplitFactoryBuilder.build(SplitFactoryBuilder.java:67)
       at com.envoy.app.utils.SplitProvider.initScope(SplitProvider.java:77)
       at com.envoy.app.utils.SplitProvider.onClientUpdate(SplitProvider.java:95)
       at com.envoy.app.ui.screens.office.OfficeViewModel.loadOfficeActions(OfficeViewModel.java:210)
       at com.envoy.app.ui.screens.office.OfficeViewModel$1.invoke(OfficeViewModel.java:155)
       at com.envoy.app.ui.screens.office.OfficeViewModel$1.invoke(OfficeViewModel.java:83)
       at com.envoy.app.account.UserManager$observeUserUpdates$1.invokeSuspend(UserManager.java:204)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:33)
       at kotlinx.coroutines.DispatchedContinuation.resumeUndispatchedWith(DispatchedContinuation.java:226)
       at kotlinx.coroutines.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuationKt.java:333)
       at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(CancellableKt.java:26)
       at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.java:109)
       at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.java:158)
       at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(BuildersKt__Builders_commonKt.java:56)
       at kotlinx.coroutines.BuildersKt.launch(BuildersKt.java:1)
       at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(BuildersKt__Builders_commonKt.java:49)
       at kotlinx.coroutines.BuildersKt.launch$default(BuildersKt.java:1)
       at com.envoy.app.account.UserManager.observeUserUpdates(UserManager.java:203)
       at com.envoy.app.ui.screens.office.OfficeViewModel.<init>(OfficeViewModel.java:154)
       at java.lang.reflect.Constructor.newInstance0(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
       at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.java:267)
       at androidx.lifecycle.SavedStateViewModelFactory.create(SavedStateViewModelFactory.java:106)
       at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:185)
       at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:150)
       at com.android.tools.r8.GeneratedOutlineSupport.outline7(GeneratedOutlineSupport.java:8)
       at com.envoy.app.di.modules.ViewModelModule.providesOfficeViewModel(ViewModelModule.java:7)
       at com.envoy.app.di.modules.ViewModelModule_ProvidesOfficeViewModelFactory.providesOfficeViewModel(ViewModelModule_ProvidesOfficeViewModelFactory.java:37)
       at com.envoy.app.di.components.DaggerActivityComponent.getOfficeViewModel(DaggerActivityComponent.java:221)
       at com.envoy.app.di.components.DaggerActivityComponent.injectOfficeActivity(DaggerActivityComponent.java:502)
       at com.envoy.app.di.components.DaggerActivityComponent.inject(DaggerActivityComponent.java:358)
       at com.envoy.app.ui.screens.office.OfficeActivity.onCreate(OfficeActivity.java:98)
       at android.app.Activity.performCreate(Activity.java:8000)
       at android.app.Activity.performCreate(Activity.java:7984)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3404)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:223)
       at android.app.ActivityThread.main(ActivityThread.java:7660)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by chillaq** [comment]
Hi @huhx0015 , thanks for the info, checking with the team now.

Thanks
Bilal

**Comment by chillaq** [comment]
Hi @huhx0015 , 

This issue could happen if the Split factory is created with a null user key and has background sync enabled. Could you verify this from your end?

The user key is required when initializing Split factory since it will be used to query the user segments.

Hope that helps.

Thanks
Bilal

**Comment by huhx0015** [comment]
Hi @chillaq,

Thank you for investigating this issue, we appreciate it! We've investigated on our end and identified in our codebase that the Split client could be initialized with a null key. We've issued a fix to prevent this from happening.

Thank you again @chillaq!

**Comment by chillaq** [comment]
Great, thanks
