### ISSUE TITLE
SdkTargetPath.mySegments does not URL encode the Key String 

### ISSUE THREAD

**Issue by tyler-yolabs** [splitio/android-client#226]
I'm seeing a crash happen when trying to create a `SplitClient` using a matchingKey that contains non-URL encoded characters (to be specific, `|`).

We're getting this key from our auth provider, Auth0, and the key is in the format `auth0|uuid`. We'd like to be able to use this string as the matching key, and not need to manually URL-encode that string everywhere else we use it in our systems.

Split SDK version: `2.6.8`

Stacktrace:
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: xx.xx.xxx.android.xxx, PID: 28442
    java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
     Caused by: java.net.URISyntaxException: Illegal character in path at index 41: https://sdk.split.io/api/mySegments/auth0|randomlygeneratedcode1203234
        at java.net.URI$Parser.fail(URI.java:2893)
        at java.net.URI$Parser.checkChars(URI.java:3066)
        at java.net.URI$Parser.parseHierarchical(URI.java:3150)
        at java.net.URI$Parser.parse(URI.java:3098)
        at java.net.URI.<init>(URI.java:584)
        at io.split.android.client.network.SdkTargetPath.buildUrl(SdkTargetPath.java:47)
        at io.split.android.client.network.SdkTargetPath.buildUrl(SdkTargetPath.java:39)
        at io.split.android.client.network.SdkTargetPath.mySegments(SdkTargetPath.java:23)
        at io.split.android.client.service.ServiceFactory.getMySegmentsFetcher(ServiceFactory.java:63)
        at io.split.android.client.SplitFactoryHelper.buildApiFacade(SplitFactoryHelper.java:97)
        at io.split.android.client.SplitFactoryImpl.<init>(SplitFactoryImpl.java:164)
        at io.split.android.client.SplitFactoryImpl.<init>(SplitFactoryImpl.java:84)
        at io.split.android.client.SplitFactoryBuilder.build(SplitFactoryBuilder.java:67)
        at xx.xxx.xxx.service.feature_flag.NativeSplitIoClient.<init>(NativeSplitIoClient.kt:29)
```

**Comment by chillaq** [comment]
Hi Tyler, thanks for the info, I will escalate to Engineering, the same character works fine with server side SDKs since they don't use MySegment URL.

Thanks
Bilal

**Comment by chillaq** [comment]
Hi Tyler,

We release SDK version 2.6.9 that fixes this issue.

Thanks
Bilal
