### ISSUE TITLE
Creating a Split client on app targeting Android S (API 31) causes crash on Android S devices

### ISSUE THREAD

**Issue by joetimmins** [splitio/android-client#270]
Stack trace:

> Fatal Exception: java.lang.IllegalArgumentException: uk.co.tickr.android: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
       at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
       at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:645)
       at android.app.PendingIntent.getBroadcast(PendingIntent.java:632)
       at androidx.work.impl.utils.ForceStopRunnable.getPendingIntent(ForceStopRunnable.java:196)
       at androidx.work.impl.utils.ForceStopRunnable.isForceStopped(ForceStopRunnable.java:128)
       at androidx.work.impl.utils.ForceStopRunnable.run(ForceStopRunnable.java:93)
       at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:920)

We call `SplitFactory.client()` on app startup, and our app crashes with the above stack trace on Android S devices.

Looks like the WorkManager dependency in Split is outdated.

**Comment by joetimmins** [comment]
If we use `compileSdkVersion 31` with `targetSdkVersion 30`, the crash does not occur, but this is not a long term solution.

**Comment by chillaq** [comment]
Hi @joetimmins , could you provide the code that uses the SDK with the key value passed? 

BTW, I don't see io.split in the stack trace.

**Comment by joetimmins** [comment]
> could you provide the code that uses the SDK with the key value passed?

Sorry, I'm not following. Do you mean when we get a treatment? We do this at various different points in our app by calling `SplitClient.getTreatment(splitName)`, which we don't call at app startup. We never reach any of these points right now, because our app crashes on startup.

The reason we believe Split is causing the crash is because it uses WorkManager 2.3.1.

From the WorkManager release notes:
> Note: WorkManager Version 2.7.0 is required for apps targeting Android 12 (S).
https://developer.android.com/jetpack/androidx/releases/work?hl=pl#version_270_2

It looks like Split is still using WorkManager 2.3.1.
https://github.com/splitio/android-client/blob/dbc7fa3d0b40cf573de66e90d4f9f3d1e5903be4/build.gradle#L89

Is there any ETA on when Split will move to WorkManager 2.7.0?

**Comment by joetimmins** [comment]
We have further verified that Split is the root cause of the crash on startup on devices targeting Android S. 

We created a build with all Split dependencies removed entirely, and changed our targetSdkVersion to 31. These are the only changes from our currently released app version, which does not crash.

This build does not crash either.

**Comment by joetimmins** [comment]
Appreciate the response @chillaq - any further news on this?

**Comment by chillaq** [comment]
@joetimmins nothing yet, I pinged the team now.

**Comment by agustinona** [comment]
Hi @joetimmins,

Our engineering team looked into this but weren't able to reproduce the issue.

Since Android 12 is a preview and Work Manager 2.7.0 is still a beta version, we can't adopt it for now.

There is a similar issue posted in StackOverflow which might help you find a solution: https://stackoverflow.com/questions/68473542/mediasessioncompattargeting-s-version-31-and-above-requires-that-one-of-flag

Alternatively, you can try adding the Work Manager 2.7.0 dependency to your project and check if this resolves the issue since Gradle will use the higher release when resolving version conflicts (https://docs.gradle.org/current/userguide/dependency_resolution.html).
