### ISSUE TITLE
IllegalArgumentException on SDK 31+ devices emulators

### ISSUE THREAD

**Issue by sebdomdev** [splitio/android-client#389]
When the latest version of the Android split.io SDK is used (2.10.2) and the app is started, the app crashes with the following exception:
`java.lang.IllegalArgumentException: myapp: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
        at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
        at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:645)
        at android.app.PendingIntent.getBroadcast(PendingIntent.java:632)
        at androidx.work.impl.utils.ForceStopRunnable.getPendingIntent(ForceStopRunnable.java:285)
        at androidx.work.impl.utils.ForceStopRunnable.isForceStopped(ForceStopRunnable.java:158)
        at androidx.work.impl.utils.ForceStopRunnable.forceStopRunnable(ForceStopRunnable.java:185)
        at androidx.work.impl.utils.ForceStopRunnable.run(ForceStopRunnable.java:103)
        at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:920)`

The reason is that split.io is using androidx.work:work-runtime-ktx:2.6.0 which doesn't use the currect flags that are required on SDK level 31 and laters.

As a workaround, androidx.work:work-runtime-ktx:2.7.0 or later can be added as a dependency in the app that uses the split.io SDK. However, the dependency work-runtime-ktx should be updated to 2.7.0 or later in the split.io SDK for a proper fix.

**Comment by chillaq** [comment]
Hi @sebdomdev , thanks for the details, will check with the team.

**Comment by chillaq** [comment]
Hi @sebdomdev  , I am closing this issue, let us know if you need any further help.

Thanks
